CREATE DATABASE IF NOT EXISTS ALX_prodev;

CREATE USER IF NOT EXISTS 'NEW USER'@'%' IDENTIFIED BY 'PUT YOUR SECURE PASSWORD HERE';

GRANT ALL PRIVILEGES ON ALX_prodev.* TO 'NEW USER'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
