# Generated by Django 5.2.8 on 2025-12-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_user_managers_rename_user_id_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
